-- local rt = require("rust-tools")
--
-- rt.setup({
--   server = {
--     on_attach = function(_, bufnr)
--       -- Hover actions
--       vim.keymap.set("n", "<ledear>kk", rt.hover_actions.hover_actions, { buffer = bufnr })
--       -- Code action groups
--       vim.keymap.set("n", "<leader>rt", rt.code_action_group.code_action_group, { buffer = bufnr })
--       -- Runnables
--       -- vim.keymap.set("n", "<leader>rr", rt.runnables.runnables, { buffer = bufnr })
--     end,
--   },
-- })
