require('after.plugin.telescope')
require('after.plugin.indent_blankline')
require('after.plugin.comment')
require('after.plugin.lualine')
require('after.plugin.git_sign')
require('after.plugin.indent_blankline')
require('after.plugin.treesitter')
require('after.plugin.mason_lsp')
require('after.plugin.cmp')
-- require('after.plugin.dapui')
